public class GajiKaryawan extends javax.swing.JFrame {

    int gajipokok;
    int gajikotor;
    int pajak;
    int gajibersih;
    int t_istri;
    int t_anak;
    int j_anak;
    String t_istri_1; 
    String t_anak_1;
    String gajikotor_1;
    String pajak_1;
    String gajibersih_1;
    public GajiKaryawan() {
        setTitle("PERHITUNGAN GAJI");
        initComponents();
    }
    private void gaji(){
        int pilihan=cmbjabatan.getSelectedIndex();
        switch(pilihan){
            case 0:
                txtgajipokok.setText("7500000");
            break;    
            case 1:
                txtgajipokok.setText("5000000");
            break;
            case 2:
                txtgajipokok.setText("3000000");
            break;
            case 3:
                txtgajipokok.setText("2000000");
            break;
            case 4:
                txtgajipokok.setText("1200000");
            break;
            case 5:
                txtgajipokok.setText("750000");
            break;        
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbjabatan = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtnip = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtgajipokok = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtjumlahanak = new javax.swing.JTextField();
        txttunjangananak = new javax.swing.JTextField();
        txttunjanganistri = new javax.swing.JTextField();
        txtpajak = new javax.swing.JTextField();
        txtgajikotor = new javax.swing.JTextField();
        txtgajibersih = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cmdbersih = new javax.swing.JButton();
        cmdhitung = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        opsi1 = new javax.swing.JRadioButton();
        opsi2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("NIP");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("NAMA");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Jabatan");

        cmbjabatan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbjabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CEO", "Manajer", "Kabag", "Sekretaris", "Karyawan", "OB/OG" }));
        cmbjabatan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbjabatanItemStateChanged(evt);
            }
        });
        cmbjabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbjabatanActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Gaji Pokok");

        txtnip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnipActionPerformed(evt);
            }
        });

        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        txtgajipokok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgajipokokActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Jumlah Anak");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Tunjangan Anak (10% Gaji)");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Tunjangan Istri (15% Gaji)");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Pajak (5% Gaji)");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Gaji Kotor");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Gaji Bersih");

        txtpajak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpajakActionPerformed(evt);
            }
        });

        txtgajibersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgajibersihActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("PERHITUNGAN GAJI");

        cmdbersih.setText("Bersihkan");
        cmdbersih.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdbersihMouseClicked(evt);
            }
        });

        cmdhitung.setText("Hitung");
        cmdhitung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdhitungMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Status");

        buttonGroup1.add(opsi1);
        opsi1.setText("Menikah");
        opsi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opsi1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(opsi2);
        opsi2.setText("Belum Menikah");
        opsi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opsi2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtnip, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtnama))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtjumlahanak))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(cmdbersih))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(opsi1)
                                    .addComponent(txtgajipokok, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(opsi2))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txttunjangananak, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpajak)
                            .addComponent(txtgajikotor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txttunjanganistri)
                            .addComponent(txtgajibersih, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdhitung)))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtnip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txttunjangananak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txttunjanganistri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtpajak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtgajipokok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtgajikotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(opsi1)
                        .addComponent(jLabel11)
                        .addComponent(txtgajibersih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opsi2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtjumlahanak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdbersih)
                    .addComponent(cmdhitung))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnipActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void cmbjabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbjabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbjabatanActionPerformed

    private void txtpajakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpajakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpajakActionPerformed

    private void txtgajipokokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgajipokokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgajipokokActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        BelumMenikah();
    }//GEN-LAST:event_formWindowOpened

    private void cmbjabatanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbjabatanItemStateChanged
        bersih();
        gaji();
        if (opsi1.isSelected()==true) {
            Menikah();
        }else{
            BelumMenikah();
        }
    }//GEN-LAST:event_cmbjabatanItemStateChanged

    private void opsi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opsi1ActionPerformed
        Menikah();
    }//GEN-LAST:event_opsi1ActionPerformed

    private void opsi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opsi2ActionPerformed
        BelumMenikah();
    }//GEN-LAST:event_opsi2ActionPerformed

    private void cmdbersihMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdbersihMouseClicked
        bersih();
    }//GEN-LAST:event_cmdbersihMouseClicked

    private void cmdhitungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdhitungMouseClicked
        total();
    }//GEN-LAST:event_cmdhitungMouseClicked

    private void txtgajibersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgajibersihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgajibersihActionPerformed
    private void Menikah(){
        txttunjanganistri.setEnabled(true);
        txttunjangananak.setEnabled(true);
        txtjumlahanak.setEnabled(true);
        gajipokok=Integer.valueOf(txtgajipokok.getText());
        t_istri=(15*gajipokok)/100;
        t_istri_1=String.valueOf(t_istri);
        txttunjanganistri.setText(t_istri_1);
        if(txtjumlahanak.getText()!=""||txtjumlahanak.getText()!="0"){
            j_anak=Integer.valueOf(txtjumlahanak.getText());
            if(j_anak<=2&&j_anak>=1){
                t_anak=((10*gajipokok)/100)*j_anak;
            }else if(j_anak>2){
                t_anak=((gajipokok*10)/100)*2;
            }else{
                t_anak=0;
            }
            t_anak_1=String.valueOf(t_anak);
            txttunjangananak.setText(t_anak_1);
        }       
    }
    private void BelumMenikah(){
         t_istri=0;
         t_anak=0;
         j_anak=0;
        txttunjanganistri.setText("0");
        txttunjangananak.setText("0");
        txtjumlahanak.setText("0");
        txttunjanganistri.setEnabled(false);
        txttunjangananak.setEnabled(false);
        txtjumlahanak.setEnabled(false);
    }
    private void total(){
        gajipokok=Integer.valueOf(txtgajipokok.getText());
        if(opsi1.isSelected()==true){
         gajikotor=gajipokok+t_anak+t_istri;   
        }else{
            gajikotor=gajipokok;
        }
        pajak=(gajikotor*5)/100;
        gajibersih=gajikotor-pajak;
        gajikotor_1=String.valueOf(gajikotor);
        pajak_1=String.valueOf(pajak);
        gajibersih_1=String.valueOf(gajibersih);
        txtgajikotor.setText(gajikotor_1);
        txtpajak.setText(pajak_1);
        txtgajibersih.setText(gajibersih_1);
    }
     private void bersih(){
         gajipokok=0;
         gajikotor=0;
         pajak=0;
         gajibersih=0;
         t_istri=0;
         t_anak=0;
         j_anak=0;
        txtgajipokok.setText("0");
        txttunjanganistri.setText("0");
        txtjumlahanak.setText("0");
        txttunjangananak.setText("0");
        txtgajikotor.setText("0");
        txtpajak.setText("0");
        txtgajibersih.setText("0");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GajiKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GajiKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GajiKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GajiKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GajiKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbjabatan;
    private javax.swing.JButton cmdbersih;
    private javax.swing.JButton cmdhitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton opsi1;
    private javax.swing.JRadioButton opsi2;
    private javax.swing.JTextField txtgajibersih;
    private javax.swing.JTextField txtgajikotor;
    private javax.swing.JTextField txtgajipokok;
    private javax.swing.JTextField txtjumlahanak;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnip;
    private javax.swing.JTextField txtpajak;
    private javax.swing.JTextField txttunjangananak;
    private javax.swing.JTextField txttunjanganistri;
    // End of variables declaration//GEN-END:variables
}
